// <auto-generated />
using System;
using API.Compsesa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Compsesa.Data.Migrations
{
    [DbContext(typeof(APICompsesaContext))]
    partial class APICompsesaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Compsesa.Shared.Entities.DatosSensores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Codigo_Parametro")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha_Dato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre_Parametro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Parametro_Sensores_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor_Numero")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("DatosSensores");
                });

            modelBuilder.Entity("API.Compsesa.Shared.Entities.Sensores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Codigo_Parametro")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion_Corta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion_Larga")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion_Med")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_Modificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacione")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sensores");
                });
#pragma warning restore 612, 618
        }
    }
}
